const ProtocolInfo = {};

/**
 * NOTE TO DEVELOPERS
 * Do not waste your time or ours submitting pull requests changing game and/or protocol version numbers.
 * Pull requests changing game and/or protocol version numbers will be closed.
 *
 * This file is generated automatically, do not edit it manually.
 */

/**
 * Actual Minecraft: PE protocol version
 */
ProtocolInfo.PROTOCOL = 408;
/**
 * Version number sent to clients in ping responses.
 */
ProtocolInfo.VERSION = "1.16.20";

ProtocolInfo.LOGIN_PACKET = 0x01;
ProtocolInfo.PLAY_STATUS_PACKET = 0x02;
ProtocolInfo.SERVER_TO_CLIENT_HANDSHAKE_PACKET = 0x03;
ProtocolInfo.CLIENT_TO_SERVER_HANDSHAKE_PACKET = 0x04;
ProtocolInfo.DISCONNECT_PACKET = 0x05;
ProtocolInfo.RESOURCE_PACKS_INFO_PACKET = 0x06;
ProtocolInfo.RESOURCE_PACK_STACK_PACKET = 0x07;
ProtocolInfo.RESOURCE_PACK_CLIENT_RESPONSE_PACKET = 0x08;
ProtocolInfo.TEXT_PACKET = 0x09;
ProtocolInfo.SET_TIME_PACKET = 0x0a;
ProtocolInfo.START_GAME_PACKET = 0x0b;
ProtocolInfo.ADD_PLAYER_PACKET = 0x0c;
ProtocolInfo.ADD_ACTOR_PACKET = 0x0d;
ProtocolInfo.REMOVE_ACTOR_PACKET = 0x0e;
ProtocolInfo.ADD_ITEM_ACTOR_PACKET = 0x0f;

ProtocolInfo.TAKE_ITEM_ACTOR_PACKET = 0x11;
ProtocolInfo.MOVE_ACTOR_ABSOLUTE_PACKET = 0x12;
ProtocolInfo.MOVE_PLAYER_PACKET = 0x13;
ProtocolInfo.RIDER_JUMP_PACKET = 0x14;
ProtocolInfo.UPDATE_BLOCK_PACKET = 0x15;
ProtocolInfo.ADD_PAINTING_PACKET = 0x16;
ProtocolInfo.TICK_SYNC_PACKET = 0x17;
ProtocolInfo.LEVEL_SOUND_EVENT_PACKET_V1 = 0x18;
ProtocolInfo.LEVEL_EVENT_PACKET = 0x19;
ProtocolInfo.BLOCK_EVENT_PACKET = 0x1a;
ProtocolInfo.ACTOR_EVENT_PACKET = 0x1b;
ProtocolInfo.MOB_EFFECT_PACKET = 0x1c;
ProtocolInfo.UPDATE_ATTRIBUTES_PACKET = 0x1d;
ProtocolInfo.INVENTORY_TRANSACTION_PACKET = 0x1e;
ProtocolInfo.MOB_EQUIPMENT_PACKET = 0x1f;
ProtocolInfo.MOB_ARMOR_EQUIPMENT_PACKET = 0x20;
ProtocolInfo.INTERACT_PACKET = 0x21;
ProtocolInfo.BLOCK_PICK_REQUEST_PACKET = 0x22;
ProtocolInfo.ACTOR_PICK_REQUEST_PACKET = 0x23;
ProtocolInfo.PLAYER_ACTION_PACKET = 0x24;
ProtocolInfo.ACTOR_FALL_PACKET = 0x25;
ProtocolInfo.HURT_ARMOR_PACKET = 0x26;
ProtocolInfo.SET_ACTOR_DATA_PACKET = 0x27;
ProtocolInfo.SET_ACTOR_MOTION_PACKET = 0x28;
ProtocolInfo.SET_ACTOR_LINK_PACKET = 0x29;
ProtocolInfo.SET_HEALTH_PACKET = 0x2a;
ProtocolInfo.SET_SPAWN_POSITION_PACKET = 0x2b;
ProtocolInfo.ANIMATE_PACKET = 0x2c;
ProtocolInfo.RESPAWN_PACKET = 0x2d;
ProtocolInfo.CONTAINER_OPEN_PACKET = 0x2e;
ProtocolInfo.CONTAINER_CLOSE_PACKET = 0x2f;
ProtocolInfo.PLAYER_HOTBAR_PACKET = 0x30;
ProtocolInfo.INVENTORY_CONTENT_PACKET = 0x31;
ProtocolInfo.INVENTORY_SLOT_PACKET = 0x32;
ProtocolInfo.CONTAINER_SET_DATA_PACKET = 0x33;
ProtocolInfo.CRAFTING_DATA_PACKET = 0x34;
ProtocolInfo.CRAFTING_EVENT_PACKET = 0x35;
ProtocolInfo.GUI_DATA_PICK_ITEM_PACKET = 0x36;
ProtocolInfo.ADVENTURE_SETTINGS_PACKET = 0x37;
ProtocolInfo.BLOCK_ACTOR_DATA_PACKET = 0x38;
ProtocolInfo.PLAYER_INPUT_PACKET = 0x39;
ProtocolInfo.LEVEL_CHUNK_PACKET = 0x3a;
ProtocolInfo.SET_COMMANDS_ENABLED_PACKET = 0x3b;
ProtocolInfo.SET_DIFFICULTY_PACKET = 0x3c;
ProtocolInfo.CHANGE_DIMENSION_PACKET = 0x3d;
ProtocolInfo.SET_PLAYER_GAME_TYPE_PACKET = 0x3e;
ProtocolInfo.PLAYER_LIST_PACKET = 0x3f;
ProtocolInfo.SIMPLE_EVENT_PACKET = 0x40;
ProtocolInfo.EVENT_PACKET = 0x41;
ProtocolInfo.SPAWN_EXPERIENCE_ORB_PACKET = 0x42;
ProtocolInfo.CLIENTBOUND_MAP_ITEM_DATA_PACKET = 0x43;
ProtocolInfo.MAP_INFO_REQUEST_PACKET = 0x44;
ProtocolInfo.REQUEST_CHUNK_RADIUS_PACKET = 0x45;
ProtocolInfo.CHUNK_RADIUS_UPDATED_PACKET = 0x46;
ProtocolInfo.ITEM_FRAME_DROP_ITEM_PACKET = 0x47;
ProtocolInfo.GAME_RULES_CHANGED_PACKET = 0x48;
ProtocolInfo.CAMERA_PACKET = 0x49;
ProtocolInfo.BOSS_EVENT_PACKET = 0x4a;
ProtocolInfo.SHOW_CREDITS_PACKET = 0x4b;
ProtocolInfo.AVAILABLE_COMMANDS_PACKET = 0x4c;
ProtocolInfo.COMMAND_REQUEST_PACKET = 0x4d;
ProtocolInfo.COMMAND_BLOCK_UPDATE_PACKET = 0x4e;
ProtocolInfo.COMMAND_OUTPUT_PACKET = 0x4f;
ProtocolInfo.UPDATE_TRADE_PACKET = 0x50;
ProtocolInfo.UPDATE_EQUIP_PACKET = 0x51;
ProtocolInfo.RESOURCE_PACK_DATA_INFO_PACKET = 0x52;
ProtocolInfo.RESOURCE_PACK_CHUNK_DATA_PACKET = 0x53;
ProtocolInfo.RESOURCE_PACK_CHUNK_REQUEST_PACKET = 0x54;
ProtocolInfo.TRANSFER_PACKET = 0x55;
ProtocolInfo.PLAY_SOUND_PACKET = 0x56;
ProtocolInfo.STOP_SOUND_PACKET = 0x57;
ProtocolInfo.SET_TITLE_PACKET = 0x58;
ProtocolInfo.ADD_BEHAVIOR_TREE_PACKET = 0x59;
ProtocolInfo.STRUCTURE_BLOCK_UPDATE_PACKET = 0x5a;
ProtocolInfo.SHOW_STORE_OFFER_PACKET = 0x5b;
ProtocolInfo.PURCHASE_RECEIPT_PACKET = 0x5c;
ProtocolInfo.PLAYER_SKIN_PACKET = 0x5d;
ProtocolInfo.SUB_CLIENT_LOGIN_PACKET = 0x5e;
ProtocolInfo.AUTOMATION_CLIENT_CONNECT_PACKET = 0x5f;
ProtocolInfo.SET_LAST_HURT_BY_PACKET = 0x60;
ProtocolInfo.BOOK_EDIT_PACKET = 0x61;
ProtocolInfo.NPC_REQUEST_PACKET = 0x62;
ProtocolInfo.PHOTO_TRANSFER_PACKET = 0x63;
ProtocolInfo.MODAL_FORM_REQUEST_PACKET = 0x64;
ProtocolInfo.MODAL_FORM_RESPONSE_PACKET = 0x65;
ProtocolInfo.SERVER_SETTINGS_REQUEST_PACKET = 0x66;
ProtocolInfo.SERVER_SETTINGS_RESPONSE_PACKET = 0x67;
ProtocolInfo.SHOW_PROFILE_PACKET = 0x68;
ProtocolInfo.SET_DEFAULT_GAME_TYPE_PACKET = 0x69;
ProtocolInfo.REMOVE_OBJECTIVE_PACKET = 0x6a;
ProtocolInfo.SET_DISPLAY_OBJECTIVE_PACKET = 0x6b;
ProtocolInfo.SET_SCORE_PACKET = 0x6c;
ProtocolInfo.LAB_TABLE_PACKET = 0x6d;
ProtocolInfo.UPDATE_BLOCK_SYNCED_PACKET = 0x6e;
ProtocolInfo.MOVE_ACTOR_DELTA_PACKET = 0x6f;
ProtocolInfo.SET_SCOREBOARD_IDENTITY_PACKET = 0x70;
ProtocolInfo.SET_LOCAL_PLAYER_AS_INITIALIZED_PACKET = 0x71;
ProtocolInfo.UPDATE_SOFT_ENUM_PACKET = 0x72;
ProtocolInfo.NETWORK_STACK_LATENCY_PACKET = 0x73;

ProtocolInfo.SCRIPT_CUSTOM_EVENT_PACKET = 0x75;
ProtocolInfo.SPAWN_PARTICLE_EFFECT_PACKET = 0x76;
ProtocolInfo.AVAILABLE_ACTOR_IDENTIFIERS_PACKET = 0x77;
ProtocolInfo.LEVEL_SOUND_EVENT_PACKET_V2 = 0x78;
ProtocolInfo.NETWORK_CHUNK_PUBLISHER_UPDATE_PACKET = 0x79;
ProtocolInfo.BIOME_DEFINITION_LIST_PACKET = 0x7a;
ProtocolInfo.LEVEL_SOUND_EVENT_PACKET = 0x7b;
ProtocolInfo.LEVEL_EVENT_GENERIC_PACKET = 0x7c;
ProtocolInfo.LECTERN_UPDATE_PACKET = 0x7d;
ProtocolInfo.ADD_ENTITY_PACKET = 0x7f;
ProtocolInfo.REMOVE_ENTITY_PACKET = 0x80;
ProtocolInfo.CLIENT_CACHE_STATUS_PACKET = 0x81;
ProtocolInfo.ON_SCREEN_TEXTURE_ANIMATION_PACKET = 0x82;
ProtocolInfo.MAP_CREATE_LOCKED_COPY_PACKET = 0x83;
ProtocolInfo.STRUCTURE_TEMPLATE_DATA_REQUEST_PACKET = 0x84;
ProtocolInfo.STRUCTURE_TEMPLATE_DATA_RESPONSE_PACKET = 0x85;
ProtocolInfo.UPDATE_BLOCK_PROPERTIES_PACKET = 0x86;
ProtocolInfo.CLIENT_CACHE_BLOB_STATUS_PACKET = 0x87;
ProtocolInfo.CLIENT_CACHE_MISS_RESPONSE_PACKET = 0x88;
ProtocolInfo.EDUCATION_SETTINGS_PACKET = 0x89;
ProtocolInfo.EMOTE_PACKET = 0x8a;
ProtocolInfo.MULTIPLAYER_SETTINGS_PACKET = 0x8b;
ProtocolInfo.SETTINGS_COMMAND_PACKET = 0x8c;
ProtocolInfo.ANVIL_DAMAGE_PACKET = 0x8d;
ProtocolInfo.COMPLETED_USING_ITEM_PACKET = 0x8e;
ProtocolInfo.NETWORK_SETTINGS_PACKET = 0x8f;
ProtocolInfo.PLAYER_AUTH_INPUT_PACKET = 0x90;
ProtocolInfo.CREATIVE_CONTENT_PACKET = 0x91;
ProtocolInfo.PLAYER_ENCHANT_OPTIONS_PACKET = 0x92;
ProtocolInfo.ITEM_STACK_REQUEST_PACKET = 0x93;
ProtocolInfo.ITEM_STACK_RESPONSE_PACKET = 0x94;
ProtocolInfo.PLAYER_ARMOR_DAMAGE_PACKET = 0x95;
ProtocolInfo.CODE_BUILDER_PACKET = 0x96;
ProtocolInfo.UPDATE_PLAYER_GAME_TYPE_PACKET = 0x97;
ProtocolInfo.EMOTE_LIST_PACKET = 0x98;
ProtocolInfo.POSITION_TRACKING_D_B_SERVER_BROADCAST_PACKET = 0x99;
ProtocolInfo.POSITION_TRACKING_D_B_CLIENT_REQUEST_PACKET = 0x9a;
ProtocolInfo.DEBUG_INFO_PACKET = 0x9b;
ProtocolInfo.PACKET_VIOLATION_WARNING_PACKET = 0x9c;

module.exports = ProtocolInfo;
